# Generated by Django 5.2.6 on 2025-11-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_grade_class_teacher_markentry_reportcard_and_more'),
        ('core', '0003_alter_user_role_alter_academicyear_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Primary', 'Primary'), ('O-Level', 'O-Level'), ('A-Level', 'A-Level')], max_length=20)),
                ('name', models.CharField(default='Uganda Curriculum', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_systems', to='core.school')),
            ],
            options={
                'verbose_name_plural': 'Grading Systems',
                'unique_together': {('school', 'level')},
            },
        ),
        migrations.CreateModel(
            name='PromotionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_average_score', models.DecimalField(decimal_places=2, help_text='Minimum average score to promote', max_digits=5)),
                ('min_subjects_passed', models.IntegerField(default=5, help_text='Minimum number of subjects that must be passed')),
                ('required_core_subjects', models.CharField(blank=True, help_text="Comma-separated list of required core subjects (e.g., 'Mathematics,English,Science')", max_length=255)),
                ('max_failures_allowed', models.IntegerField(default=2, help_text='Maximum number of subjects that can be failed')),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_criteria', to='academics.gradingsystem')),
            ],
            options={
                'verbose_name_plural': 'Promotion Criteria',
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='Grade letter (e.g., A, B, C, D, E, F)', max_length=10)),
                ('min_score', models.DecimalField(decimal_places=2, help_text='Minimum percentage score', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum percentage score', max_digits=5)),
                ('points', models.DecimalField(decimal_places=2, help_text='Points value (e.g., 9 for A*, 8 for A)', max_digits=5)),
                ('remark', models.CharField(help_text='Remark (e.g., Excellent, Very Good, Good, Pass, Fail)', max_length=100)),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='academics.gradingsystem')),
            ],
            options={
                'ordering': ['-min_score'],
                'unique_together': {('grading_system', 'grade')},
            },
        ),
    ]
