# Generated by Django 5.2.6 on 2025-11-02 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_gradingsystem_promotioncriteria_gradescale'),
        ('core', '0003_alter_user_role_alter_academicyear_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='level',
            field=models.CharField(choices=[('P', 'Primary'), ('O', 'O-Level'), ('A', 'A-Level')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('P', 'Primary'), ('O', 'O-Level'), ('A', 'A-Level')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='core.school')),
            ],
            options={
                'unique_together': {('school', 'grade', 'name')},
            },
        ),
    ]
