# Generated by Django 5.2.6 on 2025-11-02 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_grade_level_alter_subject_level_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markentry',
            name='ca_score',
        ),
        migrations.RemoveField(
            model_name='markentry',
            name='exam_score',
        ),
        migrations.RemoveField(
            model_name='markentry',
            name='total_score',
        ),
        migrations.AddField(
            model_name='markentry',
            name='comments',
            field=models.TextField(blank=True, help_text="Teacher's comments"),
        ),
        migrations.AddField(
            model_name='markentry',
            name='exam_type',
            field=models.CharField(choices=[('BOT', 'Beginning of Term'), ('MID', 'Mid Term'), ('EOT', 'End of Term')], default='EOT', max_length=3),
        ),
        migrations.AddField(
            model_name='markentry',
            name='score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exam score (0-100)', max_digits=5),
        ),
    ]
