# Generated by Django 5.2.7 on 2025-11-02 19:43

from django.db import migrations


def cleanup_grades_by_school_type(apps, schema_editor):
    """Remove grades that don't belong to the school type"""
    Grade = apps.get_model("academics", "Grade")
    School = apps.get_model("core", "School")
    
    # Delete grades that don't match school type
    deleted_count = 0
    for grade in Grade.objects.all():
        if grade.school.school_type == 'primary' and grade.level != 'P':
            # Primary school with non-primary grades - delete
            grade.delete()
            deleted_count += 1
        elif grade.school.school_type == 'high' and grade.level == 'P':
            # High school with primary grades - delete
            grade.delete()
            deleted_count += 1
    
    print(f"Deleted {deleted_count} grades that didn't match school types")


def reverse_cleanup_grades(apps, schema_editor):
    """Reverse migration - cannot restore deleted data"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_markentry_ca_score_and_more'),
        ('core', '0004_school_school_type'),
    ]

    operations = [
        migrations.RunPython(cleanup_grades_by_school_type, reverse_code=reverse_cleanup_grades),
    ]
