# Generated by Django 5.2.7 on 2025-11-02 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_auto_20251102_2243'),
        ('core', '0005_add_user_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Combination name (e.g., PCM, BAM, Literature, etc.)', max_length=64)),
                ('code', models.CharField(blank=True, help_text='Optional code for the combination', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(limit_choices_to={'level': 'A'}, on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='academics.grade')),
            ],
            options={
                'verbose_name': 'A-Level Combination',
                'verbose_name_plural': 'A-Level Combinations',
                'unique_together': {('grade', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stream',
            name='combination',
            field=models.ForeignKey(blank=True, help_text='A-Level combination (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.combination'),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('school', 'grade', 'combination', 'name')},
        ),
    ]
