# Generated by Django 5.2.7 on 2025-11-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_combination_alter_stream_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='aggregate',
            field=models.IntegerField(blank=True, help_text='Sum of all subject grades (lower is better)', null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='division',
            field=models.CharField(blank=True, help_text='Division (1-4) for Primary schools', max_length=10),
        ),
    ]
