# Generated by Django 5.2.7 on 2025-11-03 07:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_add_aggregate_division_to_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='aggregate',
            field=models.IntegerField(blank=True, help_text='Sum of grades (all for Primary, best-8 for O-Level)', null=True),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='division',
            field=models.CharField(blank=True, help_text='Division (1-4/U) for Primary and O-Level schools', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total points (A-Level: sum of all subject points)', max_digits=6),
        ),
    ]
