# Generated by Django 5.2.7 on 2025-11-03 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_update_secondary_grading'),
        ('core', '0005_add_user_profile_fields'),
        ('students', '0004_set_student_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markentry',
            options={'ordering': ['-date_entered']},
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exam name (e.g., CAT 1, Mid-Term, End of Term)', max_length=255)),
                ('percentage_weight', models.DecimalField(decimal_places=2, help_text='Percentage weight (e.g., 30.00 for 30%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Active exams can be used for mark entry')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.term')),
            ],
            options={
                'verbose_name': 'Exam/Assessment',
                'verbose_name_plural': 'Exams/Assessments',
                'ordering': ['term', 'order', 'name'],
                'unique_together': {('school', 'term', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='markentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='markentry',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='The exam/assessment this mark is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='academics.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='markentry',
            unique_together={('enrollment', 'subject', 'exam')},
        ),
        migrations.RemoveField(
            model_name='markentry',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='markentry',
            name='term',
        ),
    ]
