# Generated by Django 5.2.7 on 2025-11-04 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_add_exam_model_and_update_markentry'),
        ('students', '0006_add_medical_records_to_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='markentry',
            index=models.Index(fields=['enrollment', 'subject', 'exam'], name='academics_m_enrollm_5fb6c1_idx'),
        ),
    ]
