# Generated by Django 5.2.7 on 2025-11-05 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_add_combination_to_enrollment'),
        ('students', '0007_add_combination_to_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects in this combination', related_name='combinations', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_papers',
            field=models.BooleanField(default=False, help_text='Subject has multiple papers (e.g., Literature, Mathematics)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_compulsory',
            field=models.BooleanField(default=False, help_text='Compulsory subject for O-Level (automatically assigned)'),
        ),
        migrations.CreateModel(
            name='SubjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Paper name (e.g., 'Paper 1', 'Paper 2', 'Pure Mathematics', 'Applied Mathematics')", max_length=255)),
                ('paper_number', models.IntegerField(blank=True, help_text='Paper number for ordering (1, 2, 3, etc.)', null=True)),
                ('code', models.CharField(blank=True, help_text='Paper code (e.g., LIT1, LIT2, MATH-PURE)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Paper',
                'verbose_name_plural': 'Subject Papers',
                'ordering': ['subject', 'paper_number', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='markentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='markentry',
            name='subject_paper',
            field=models.ForeignKey(blank=True, help_text='Subject paper (if subject has papers)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subjectpaper'),
        ),
        migrations.AlterUniqueTogether(
            name='markentry',
            unique_together={('enrollment', 'subject', 'subject_paper', 'exam')},
        ),
    ]
