# Generated by Django 5.2.7 on 2025-11-05 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_add_subject_papers_combinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combination',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Optional: Leave blank to make combination available for all A-Level grades', limit_choices_to={'level': 'A'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combinations', to='academics.grade'),
        ),
    ]
