# Generated by Django 5.2.7 on 2025-11-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_combination_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='subsidiary_choice',
            field=models.CharField(choices=[('auto', 'Auto (Based on Principals)'), ('sub_math', 'Subsidiary Mathematics'), ('sub_ict', 'Subsidiary ICT')], default='auto', help_text="Which subsidiary to assign (Sub-Math or Sub-ICT). 'Auto' will determine based on principal subjects.", max_length=10),
        ),
    ]
