# Generated by Django 5.2.7 on 2025-11-06 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_combination_subsidiary_choice'),
        ('core', '0005_add_user_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UACEGradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_1_min', models.DecimalField(decimal_places=2, default=80.0, help_text='Minimum mark for D1 (Grade 1)', max_digits=5)),
                ('grade_1_max', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum mark for D1 (Grade 1)', max_digits=5)),
                ('grade_2_min', models.DecimalField(decimal_places=2, default=75.0, max_digits=5)),
                ('grade_2_max', models.DecimalField(decimal_places=2, default=79.9, max_digits=5)),
                ('grade_3_min', models.DecimalField(decimal_places=2, default=66.0, max_digits=5)),
                ('grade_3_max', models.DecimalField(decimal_places=2, default=74.9, max_digits=5)),
                ('grade_4_min', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('grade_4_max', models.DecimalField(decimal_places=2, default=65.9, max_digits=5)),
                ('grade_5_min', models.DecimalField(decimal_places=2, default=55.0, max_digits=5)),
                ('grade_5_max', models.DecimalField(decimal_places=2, default=59.9, max_digits=5)),
                ('grade_6_min', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('grade_6_max', models.DecimalField(decimal_places=2, default=54.9, max_digits=5)),
                ('grade_7_min', models.DecimalField(decimal_places=2, default=45.0, max_digits=5)),
                ('grade_7_max', models.DecimalField(decimal_places=2, default=49.9, max_digits=5)),
                ('grade_8_min', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('grade_8_max', models.DecimalField(decimal_places=2, default=44.9, max_digits=5)),
                ('grade_9_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grade_9_max', models.DecimalField(decimal_places=2, default=39.9, max_digits=5)),
                ('points_a', models.IntegerField(default=6, help_text='Points for grade A')),
                ('points_b', models.IntegerField(default=5)),
                ('points_c', models.IntegerField(default=4)),
                ('points_d', models.IntegerField(default=3)),
                ('points_e', models.IntegerField(default=2)),
                ('points_o', models.IntegerField(default=1)),
                ('points_f', models.IntegerField(default=0)),
                ('points_subsidiary_pass', models.IntegerField(default=1, help_text='Points for subsidiary Pass')),
                ('points_subsidiary_fail', models.IntegerField(default=0, help_text='Points for subsidiary Fail')),
                ('subsidiary_pass_max_grade', models.IntegerField(default=6, help_text='Maximum numerical grade (1-6) for subsidiary Pass')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uace_grading_configs', to='core.school')),
            ],
            options={
                'verbose_name': 'UACE Grading Configuration',
                'verbose_name_plural': 'UACE Grading Configurations',
                'unique_together': {('school',)},
            },
        ),
    ]
