# Generated by Django 5.2.7 on 2025-11-07 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_uacegradingconfig'),
        ('students', '0008_add_subject_papers_combinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='papers',
            field=models.ManyToManyField(blank=True, help_text='Specific papers this teacher teaches (leave empty to teach all papers)', related_name='teacher_assignments', to='academics.subjectpaper'),
        ),
        migrations.CreateModel(
            name='StudentPaperAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_assignments', to='students.enrollment')),
                ('papers', models.ManyToManyField(help_text='Papers assigned to this student for this subject', related_name='student_assignments', to='academics.subjectpaper')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'verbose_name': 'Student Paper Assignment',
                'verbose_name_plural': 'Student Paper Assignments',
                'unique_together': {('enrollment', 'subject')},
            },
        ),
    ]
