# Generated by Django 5.2.7 on 2025-11-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_teachersubject_papers_studentpaperassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='paper_selection_mode',
            field=models.CharField(choices=[('selective', 'Selective Papers (Students/Teachers choose which papers)'), ('all_compulsory', 'All Papers Compulsory (All papers automatically assigned)')], default='selective', help_text='If subject has papers, choose whether papers are selective (students/teachers choose) or all compulsory (all papers assigned automatically)', max_length=20),
        ),
    ]
