# Generated by Django 5.2.7 on 2025-11-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_subject_paper_selection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='has_elective_papers',
            field=models.BooleanField(default=False, help_text='Subject has elective papers that students/teachers can choose from (e.g., History, Art, French). Only these subjects appear when assigning papers.'),
        ),
    ]
