# Generated by Django 5.2.6 on 2025-11-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_academic_year_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('headteacher', 'Headteacher'), ('director_of_studies', 'Director of Studies'), ('teacher', 'Teacher'), ('bursar', 'Bursar'), ('parent', 'Parent'), ('student', 'Student')], default='parent', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'name')},
        ),
    ]
