# Generated by Django 5.2.7 on 2025-11-02 19:39

from django.db import migrations, models


def set_school_types(apps, schema_editor):
    """Set school types based on school names"""
    School = apps.get_model("core", "School")
    
    # Set school types based on name patterns
    for school in School.objects.all():
        name_lower = school.name.lower()
        if 'primary' in name_lower or 'kps' in name_lower.lower():
            school.school_type = 'primary'
        elif 'high' in name_lower or 'secondary' in name_lower or 'khs' in name_lower.lower():
            school.school_type = 'high'
        else:
            # Default to primary if unclear
            school.school_type = 'primary'
        school.save(update_fields=['school_type'])


def reverse_set_school_types(apps, schema_editor):
    """Reverse migration - set all to default"""
    School = apps.get_model("core", "School")
    School.objects.all().update(school_type='primary')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role_alter_academicyear_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('primary', 'Primary School'), ('high', 'High School')], default='primary', help_text='Primary school for P1-P7, High school for S1-S6', max_length=20),
        ),
        migrations.RunPython(set_school_types, reverse_code=reverse_set_school_types),
    ]
