# Generated by Django 5.2.7 on 2025-11-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='seal',
            field=models.ImageField(blank=True, help_text='Unique school seal/stamp (hard to duplicate)', null=True, upload_to='school_seals/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='School badge/logo for watermark', null=True, upload_to='school_logos/'),
        ),
    ]
