# Generated by Django 6.0.4 on 2026-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_roles_and_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('school_type', models.CharField(choices=[('primary', 'Primary (P1-P7)'), ('olevel', 'Secondary O-Level (S1-S4)'), ('alevel', 'Secondary A-Level (S5-S6)'), ('combined', 'Combined (Primary + Secondary)'), ('other', 'Other')], default='primary', max_length=20)),
                ('student_count', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_interest', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('unsure', 'Not sure yet')], default='unsure', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('onboarded', 'Onboarded'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Lead',
                'verbose_name_plural': 'Platform Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
