# Generated by Django 5.2.7 on 2025-11-02 20:25

from django.db import migrations


def set_student_names_from_user(apps, schema_editor):
    """Set student names from their user accounts if available"""
    Student = apps.get_model('students', 'Student')
    User = apps.get_model('core', 'User')
    
    updated_count = 0
    for student in Student.objects.all():
        # First try to get name from user
        if student.user and hasattr(student.user, 'first_name') and hasattr(student.user, 'last_name'):
            if student.user.first_name or student.user.last_name:
                student.first_name = student.user.first_name or ''
                student.last_name = student.user.last_name or ''
                student.save(update_fields=['first_name', 'last_name'])
                updated_count += 1
                continue
        
        # If no user or user has no name, try guardian name as fallback
        if student.guardian and student.guardian.name:
            name_parts = student.guardian.name.split(' ', 1)
            student.first_name = name_parts[0] if name_parts else ''
            student.last_name = name_parts[1] if len(name_parts) > 1 else ''
            student.save(update_fields=['first_name', 'last_name'])
            updated_count += 1
    
    print(f"Updated {updated_count} students with names")


def reverse_set_student_names(apps, schema_editor):
    """Reverse migration - clear names"""
    Student = apps.get_model('students', 'Student')
    Student.objects.all().update(first_name='', last_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RunPython(set_student_names_from_user, reverse_code=reverse_set_student_names),
    ]
