# Generated by Django 5.2.7 on 2025-11-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_set_student_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
