# Generated by Django 5.2.7 on 2025-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_change_enrollment_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any allergies the student has', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, help_text="Student's blood group (e.g., A+, O-, etc.)", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='List any chronic diseases (e.g., HIV, diabetes, asthma)', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='disabilities',
            field=models.TextField(blank=True, help_text='Describe any disabilities the student has', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact person name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_chronic_diseases',
            field=models.BooleanField(default=False, help_text='Check if student has chronic diseases'),
        ),
        migrations.AddField(
            model_name='student',
            name='has_disabilities',
            field=models.BooleanField(default=False, help_text='Check if student has any disabilities'),
        ),
        migrations.AddField(
            model_name='student',
            name='has_special_care_needs',
            field=models.BooleanField(default=False, help_text='Check if student requires special care'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Additional medical information or notes', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='special_care_needs',
            field=models.TextField(blank=True, help_text='Describe special care requirements', null=True),
        ),
    ]
