# Generated by Django 5.2.7 on 2025-11-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_add_combination_to_enrollment'),
        ('students', '0006_add_medical_records_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='combination',
            field=models.ForeignKey(blank=True, help_text='A-Level combination (only for A-Level students)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.combination'),
        ),
    ]
