# Generated by Django 5.2.7 on 2025-11-05 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_add_subject_papers_combinations'),
        ('students', '0007_add_combination_to_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=True, help_text='Whether this subject is compulsory for this enrollment')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_subjects', to='students.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'verbose_name': 'Enrollment Subject',
                'verbose_name_plural': 'Enrollment Subjects',
                'ordering': ['subject__name'],
                'unique_together': {('enrollment', 'subject')},
            },
        ),
    ]
