# Generated by Django 5.2.6 on 2025-09-21 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('enrollment', 'date')},
        ),
    ]
