# Generated by Django 5.2.6 on 2025-11-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("quiz", "Quiz"),
                    ("exam", "Exam"),
                    ("assignment", "Assignment"),
                ],
                default="assignment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="duration_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Duration in minutes for timed quizzes/exams",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="start_time",
            field=models.DateTimeField(
                blank=True, help_text="Start time for timed quizzes/exams", null=True
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="external_url",
            field=models.URLField(
                blank=True, help_text="External link (YouTube, etc.)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload PDF, video, image, or document",
                null=True,
                upload_to="course_materials/",
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("doc", "Word Document"),
                    ("ppt", "PowerPoint"),
                    ("video", "Video File"),
                    ("image", "Image"),
                    ("link", "External Link"),
                    ("other", "Other"),
                ],
                default="pdf",
                max_length=20,
            ),
        ),
    ]
