# Generated by Django 5.2.6 on 2025-11-23 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0002_assignment_assignment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="allow_attachments",
            field=models.BooleanField(
                default=True, help_text="Allow students to attach files with submission"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="exam_pdf",
            field=models.FileField(
                blank=True,
                help_text="PDF file for exam",
                null=True,
                upload_to="exam_pdfs/",
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When student completed/submitted", null=True
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="is_auto_graded",
            field=models.BooleanField(
                default=False, help_text="True if quiz was auto-graded"
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="When student started the quiz/exam", null=True
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="total_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total possible score",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="submission_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded answer sheet",
                null=True,
                upload_to="assignment_submissions/",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="submission_text",
            field=models.TextField(
                blank=True, help_text="Text answer for exams/assignments"
            ),
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                    ),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        limit_choices_to={"assignment_type": "quiz"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="elearning.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="elearning.quizquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="submission_attachments/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="elearning.assignmentsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(
                        blank=True, help_text="For short answer questions"
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "points_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_answers",
                        to="elearning.assignmentsubmission",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.quizoption",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elearning.quizquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "question")},
            },
        ),
    ]
